title: Artsy Docs Manual
description: Trying to test Just the Docs out
theme: just-the-docs

url: https://pjawzk.github.io/Artsy-Docs-Manual

aux_links:
  Template Repository: https://github.com/pjawzk/Artsy-Docs-Manual
